name: etalon

services:
  bot:
    container_name: telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5252:5252"
    depends_on:
      - postgres
      - redis
      - minio

  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mikhalexandr
      POSTGRES_PASSWORD: phptop123
      POSTGRES_DB: etalon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      MINIO_ROOT_USER: mikhalexandr
      MINIO_ROOT_PASSWORD: phptop123
    command: server /data --console-address ":9002"
    volumes:
      - minio_data:/data


volumes:
  postgres_data:
  redis_data:
  minio_data:
